# Generated by Django 3.2.9 on 2022-08-05 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodcategory',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 11, 38, 40, 307469), verbose_name='创建时间'),
        ),
    ]
