# Generated by Django 3.2.9 on 2022-08-09 18:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_goodcategory_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodcategory',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 9, 18, 8, 47, 636985), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
        migrations.CreateModel(
            name='GoodsCategoryBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='品牌名')),
                ('desc', models.TextField(default='', max_length=300, verbose_name='品牌描述')),
                ('image', models.ImageField(max_length=200, upload_to='brands/')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='goods.goodcategory', verbose_name='商品类目')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'db_table': 'goods_goodsbrand',
            },
        ),
    ]
