# Generated by Django 3.2.9 on 2022-08-17 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20220811_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodcategory',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 10, 51, 21, 723376), verbose_name='创建时间'),
        ),
    ]
